import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE','itech.settings')

import django
django.setup()
from noobnews.models import Genre, VideoGame
from django.template.defaultfilters import slugify

def populate():

     # adventure_videogame =[ {"name": "God of War", "id": 14, "genre": 1, "description": "For the first time in the series, there are two main protagonists: Kratos, the former Greek God of War who remains as the only playable character, and his young son Atreus; at times, the player may passively control him. Following the death of Kratos' second wife and Atreus' mother, they journey to fulfill her promise to spread her ashes at the highest peak of the nine realms. Kratos keeps his troubled past a secret from Atreus, who is unaware of his divine nature. Along their journey, they encounter monsters and gods of the Norse world.", "rating": 4, "release": "2018-04-20", "developer": "SIE Santa Monica Studio", "publisher": "Sony Interactive Entertainment", "image": "src=\"{% static \"/noobnews-ajax.js\" %}\""},]
     adventure_videogame = [
         {"name": "Far Cry 5", "id": 1, "genre": 1, "description": "The game takes place in Hope County, a fictional region of Montana, United States. The main story revolves around the Project at Eden's Gate, a doomsday cult that rules the land under the guise of its charismatic leader, Joseph Seed. Players control an unnamed junior deputy sheriff who becomes trapped in Hope County, and must work alongside factions of a resistance to liberate the county from the despotic rule of the Seeds and Eden's Gate. Gameplay focuses on combat and exploration; players battle enemy soldiers and dangerous wildlife using a wide array of weapons. The game features many elements found in role-playing games, such as a branching storyline and side quests. The game also features a map editor, a co-operative multiplayer mode, and a competitive multiplayer mode.", "rating": 3, "release": "2018-03-27", "developer": "Ubisoft", "publisher": "Ubisoft", "image": "/static/videogameImages/farCry5.jpg"},
         {"name": "The Legend of Zelda: Breath of the Wild", "id": 56, "genre": 1, "description": "An entry in the longrunning The Legend of Zelda series, it was released for the Nintendo Switch and Wii U consoles on March 3, 2017. Breath of the Wild is set at the end of the series' timeline; the player controls Link, who awakens from a hundred-year slumber to defeat Calamity Ganon before it can destroy the kingdom of Hyrule.", "rating": 3, "release": "2017-03-03", "developer": "Nintendo", "publisher": "Nintendo", "image": "/static/videogameImages/breathOfTheWild.jpg"},
         {"name": "Legend of Zelda: Majora's Mask", "id": 3, "genre": 1, "description": "The Legend of Zelda: Majora's Mask is an action-adventure game developed and published by Nintendo for the Nintendo 64. It was released in 2000 as the sixth main installment in The Legend of Zelda series and was the second to use 3D graphics, following 1998's The Legend of Zelda: Ocarina of Time", "rating": 4, "release": "2000-04-27", "developer": "Nintendo", "publisher": "Nintendo", "image": "/static/videogameImages/majorasMask.jpg"},
         {"name": "Legend of Zelda: Ocarina of Time", "id": 4, "genre": 1, "description": "The player controls Link in the fantasy land of Hyrule on a quest to stop the evil Ganondorf, king of the Gerudo tribe, from obtaining the Triforce, a sacred wish-granting relic. He travels through time and navigates dungeons to awaken the Seven Sages, who can seal Ganondorf forever. Ocarina of Time introduced features such as a target-lock system and context-sensitive buttons that have since become common in 3D adventure games. Music plays an important role: to progress, the player must learn to play numerous songs on an ocarina, and the game was reportedly responsible for increased interest in the instrument.", "rating": 5, "release": "1998-11-21", "developer": "Nintendo", "publisher": "Nintendo", "image": "/static/videogameImages/ocarinaOfTime.jpg"},
         {"name": "Spider-Man", "id": 5, "genre": 1, "description": "In the main storyline, the super-human crime lord Mr. Negative orchestrates a plot to seize control of New York City's criminal underworld. With Mr. Negative threatening to release a deadly virus, Spider-Man must confront him and protect the city, while navigating the personal problems of his civilian persona, Peter Parker.", "rating": 5, "release": "2018-09-07", "developer": "Insomniac Games", "publisher": "Sony Interactive Entertainment", "image": "/static/videogameImages/spiderMan.jpg"},
         {"name": "Grand Theft Auto V", "id": 6, "genre": 1, "description": "Set within the fictional state of San Andreas, based on Southern California, the single-player story follows three criminals and their efforts to commit heists while under pressure from a government agency. The open-world design lets players freely roam San Andreas' open countryside and the fictional city of Los Santos, based on Los Angeles.", "rating": 5, "release": "2013-09-17", "developer": "Rockstar North", "publisher": "Rockstar Games", "image": "/static/videogameImages/grandTheft5.jpg"},
         {"name": "What Remains of Edith Finch", "id": 7, "genre": 1, "description": "The game is centered around the character of Edith Finch, the last in the Finch family line which have a perceived curse that causes all but one member of each generation to die in unusual ways. Edith has returned to her family's home off the coast of Washington state following her mother's death to explore the house they had hastily abandoned years before. She learns about her relatives and their own deaths by visiting their bedrooms, sealed off and treated as shrines to them, with each death played out in a short gameplay sequence to the player. The game is presented as an anthology of these mini-experiences, wrapped in the dramatic retelling of the family's history and fate through Edith's narration.", "rating": 5, "release": "2017-04-25", "developer": "Giant Sparrow", "publisher": "Annapurna Interactive", "image": "/static/videogameImages/whatRemainsEdith.jpg"},
         {"name": "Uncharted 4: A Thief's End", "id": 8, "genre": 1, "description": "Following Uncharted 3: Drake's Deception, it is the final Uncharted game to feature protagonist Nathan Drake (portrayed by Nolan North). Drake, retired from fortune hunting with his wife Elena, reunites with his estranged older brother Sam and longtime partner Sully to search for Captain Henry Avery's lost treasure.", "rating": 5, "release": "2016-05-10", "developer": "Naughty Dog", "publisher": "Sony Computer Entertainment", "image": "/static/videogameImages/uncharted4.jpg"},
         {"name": "Hellblade: Senua's Sacrifice", "id": 9, "genre": 1, "description": "Inspired by Norse mythology and Celtic culture, Hellblade follows Senua, a Pict warrior who must make her way to Helheim by defeating otherworldly entities and facing their challenges, in order to rescue the soul of her dead lover from the goddess Hela. In parallel, the game acts as a metaphor for the character's struggle with psychosis, as Senua, who suffers from the condition but believes it to be a curse, is haunted by an entity known as the \"Darkness\", voices in her head known as \"Furies\", and memories from her past. To properly represent psychosis, developers worked closely with neuroscientists, mental health specialists, and people suffering from the condition.", "rating": 3, "release": "2017-08-08", "developer": "Ninja Theory", "publisher": "Ninja Theory", "image": "/static/videogameImages/hellblade.jpg"},
         {"name": "Detroit: Become Human", "id": 10, "genre": 1, "description": "Detroit: Become Human is based on Quantic Dream's 2012 technology demonstration Kara; Curry returned to reprise the title role. To research the setting, the developers visited Detroit, Michigan. The script took writer and director David Cage, who consulted artificial intelligence experts, over two years to complete. They built a new engine to complement the game and cast hundreds of actors before commencing the process of shooting and animation. Philip Sheppard, Nima Fakhrara, and John Paesano served as composers for Kara, Connor, and Markus, respectively.", "rating": 3, "release": "2018-05-25", "developer": "Quantic Dream", "publisher": "Sony Interactive Entertainment", "image": "/static/videogameImages/detroit.jpg"},
         {"name": "Rise of the Tomb Raider", "id": 11, "genre": 1, "description": "Its story follows Lara Croft as she ventures into Siberia in search of the legendary city of Kitezh while battling the paramilitary organization Trinity, which intends to uncover the city's promise of immortality. Lara must traverse the environment and combat enemies with firearms and stealth as she explores semi-open hubs. In these hubs she can raid challenge tombs to unlock new rewards, complete side missions, and scavenge for resources which can be used to craft useful materials.", "rating": 3, "release": "2015-11-10", "developer": "Crystal Dynamics", "publisher": "Square Enix & Microsoft Studios", "image": "/static/videogameImages/tombRaider.jpg"},
         {"name": "Dishonored 2", "id": 12, "genre": 1, "description": "The game takes place in the fictional city of Karnaca. After Empress Emily Kaldwin is deposed by the witch Delilah Copperspoon, the player may choose between playing as either Emily or her Royal Protector and father Corvo Attano as they attempt to reclaim the throne. Both Emily and Corvo employ their own array of supernatural abilities, though the player can alternatively decide to forfeit these abilities altogether. There is a multitude of ways to complete missions, from stealth to purposeful violent conflict, navigated through a sandbox environment.", "rating": 3, "release": "2016-09-11", "developer": "Arkane Studios", "publisher": "Bethesda Softworks", "image": "/static/videogameImages/dishonored2.jpg"},
         {"name": "Wolfenstein II: The New Colossus", "id": 13, "genre": 1, "description": "The eighth main entry in the Wolfenstein series and the sequel to 2014's Wolfenstein: The New Order, the game is set in an alternate history which takes place in 1961 following the Nazi victory in the Second World War. The story follows war veteran William \"B.J.\" Blazkowicz and his efforts to fight against the Nazi regime in America.", "rating": 3, "release": "2017-10-27", "developer": "MachineGames", "publisher": "Bethesda Softworks", "image": "/static/videogameImages/wolfenstein2.jpg"},
         {"name": "God of War", "id": 14, "genre": 1, "description": "For the first time in the series, there are two main protagonists: Kratos, the former Greek God of War who remains as the only playable character, and his young son Atreus; at times, the player may passively control him. Following the death of Kratos' second wife and Atreus' mother, they journey to fulfill her promise to spread her ashes at the highest peak of the nine realms. Kratos keeps his troubled past a secret from Atreus, who is unaware of his divine nature. Along their journey, they encounter monsters and gods of the Norse world.", "rating": 4, "release": "2018-04-20", "developer": "SIE Santa Monica Studio", "publisher": "Sony Interactive Entertainment", "image": "/static/videogameImages/godOfWar.jpeg"},
         {"name": "Red Dead Redemption 2", "id": 15, "genre": 1, "description": "Set in 1899 in a fictionalized version of the Western United States, the story centers on outlaw Arthur Morgan, a member of the Van der Linde gang dealing with the decline of the Wild West whilst attempting to survive against government forces, rival gangs, and other enemies. The story also follows fellow gang member John Marston, protagonist from the first Red Dead Redemption.", "rating": 4, "release": "2018-10-26", "developer": "Rockstar Studios", "publisher": "Rockstar Games", "image": "/static/videogameImages/redDead2.jpeg"},
         {"name": "Metal Gear Solid V: The Phantom Pain", "id": 16, "genre": 1, "description": "Set in 1984, nine years after the events of Ground Zeroes and a decade before the events of the original Metal Gear, the story follows mercenary leader Punished \"Venom\" Snake as he ventures into Soviet-occupied Afghanistan and the Angola–Zaire border region to exact revenge on the people who destroyed his forces and came close to killing him during the climax of Ground Zeroes. It carries over the tagline of Tactical Espionage Operations first used in Metal Gear Solid: Peace Walker.", "rating": 4, "release": "2015-09-01", "developer": "Kojima Productions", "publisher": "Konami Digital Entertainment", "image": "/static/videogameImages/metalGear5.jpg"}, ]

     fighting_videogame = [
         {"name": "Super Smash Bros. Ultimate", "id": 17, "genre": 1, "description": "The game follows the series' traditional style of gameplay: controlling one of various characters, players must use differing attacks to weaken their opponents and knock them out of an arena. It features a wide variety of game modes, including a campaign for a single-player and multiplayer versus modes. Ultimate includes every playable character from previous Super Smash Bros. games—ranging from Nintendo's mascots to characters from third-party franchises—and several newcomers.", "rating": 3, "release": "2018-12-07", "developer": "Bandai Namco Studios", "publisher": "Nintendo", "image": "/static/videogameImages/superSmashUltimate.jpg"},
         {"name": "Super Smash Bros. Melee", "id": 18, "genre": 1, "description": "Melee includes all playable characters from the first game, and also adds characters from franchises such as Fire Emblem, of which no games had been released outside Japan at the time. Melee's gameplay system offers an unorthodox approach to the fighting game genre, with a counter that measures damage with increasing percentages, representing the knockback the character will experience, rather than a depleting health bar seen in most fighting games. It builds on the first game by adding new gameplay features and playable characters. Following the popularity of its multiplayer gameplay, Melee has been featured in many competitive gaming tournaments, and is one of the most popular competitive fighting games.", "rating": 3, "release": "2001-12-03", "developer": "HAL Laboratory", "publisher": "Nintendo", "image": "/static/videogameImages/superSmashMelee.png"},
         {"name": "Tekken 7", "id": 19, "genre": 1, "description": "Set shortly after the events of Tekken 6, the plot focuses on the events leading up to the final battle between martial artist Heihachi Mishima and his son, Kazuya. Tekken 7 introduces elements for the fighting system such as the Rage and the Power Crush to increase the characters' powers. Tekken 7 was a critical and commercial success, selling three million copies before the game's first anniversary.", "rating": 3, "release": "2017-06-02", "developer": "Bandai Namco Studios", "publisher": "Bandai Namco Entertainment", "image": "/static/videogameImages/tekken7.png"},
         {"name": "Street Fighter V", "id": 20, "genre": 1, "description": "Similar to the previous games in the Street Fighter series, Street Fighter V features a side-scrolling fighting gameplay system. The game also introduces the \"V-Gauge\", which builds as the player receives attacks and adds three new skills. The game features 16 characters at launch, with four of them being new to the series. A story mode and additional characters were added through updates and downloadable content.", "rating": 3, "release": "2016-02-16", "developer": "Capcom", "publisher": "Capcom", "image": "/static/videogameImages/streetFighter5.jpg"},
         {"name": "Mortal Kombat X", "id": 21, "genre": 1, "description": "Like previous Mortal Kombat games, Mortal Kombat X's gameplay consists of two players, or one player and the CPU, fighting against each other with their selected character, using a large, varied array of character specific attacks. The game contains several modes, such as a story mode, which takes place twenty-five years after the previous Mortal Kombat game, several 'Tower' modes, which feature dynamically changing challenges, numerous online modes, and the 'Krypt', a mode played in a first-person perspective where players explore the areas unlocking a variety of in-game items.", "rating": 3, "release": "2015-04-14", "developer": "NetherRealm Studios", "publisher": "Warner Bros. Interactive Entertainment", "image": "/static/videogameImages/MKX.png"},
         {"name": "Injustice 2", "id": 22, "genre": 1, "description": "The core gameplay remains similar to its predecessor, albeit with minor adjustments to returning game mechanics. Injustice 2 introduces a new feature called the Gear System, a loot-dropping system that rewards players with costume pieces and equipment that can be used to customize characters' appearances and modify their abilities and stats. According to developers, the idea for implementing a role playing game (RPG)-style progression system into a fighting game had existed since before the fall of Midway Games, the original publisher for the Mortal Kombat series. Director Ed Boon also sought to incorporate gameplay mechanics used by multiplayer shooter games, such as personalization, character creation, loot, and leveling up, into the fighting game genre, which led to the development of the Gear System.", "rating": 3, "release": "2017-05-11", "developer": "NetherRealm Studios", "publisher": "Warner Bros. Interactive Entertainment", "image": "/static/videogameImages/injustice2.jpg"},
         {"name": "Pokkén Tournament", "id": 23, "genre": 1, "description": "Pokkén Tournament is a fighting game in which two fighters battle against each other using various Pokémon, with gameplay shifting between \"Field Phase\" where the Pokémon move freely around the arena similar to Power Stone and Naruto: Ultimate Ninja Storm, and \"Duel Phase\" where they move relative to each other similar to the Tekken games. Unlike most arcade fighting games, which use a traditional joystick and buttons, the arcade version is played using console-style controllers, which are designed so that players who are not used to arcade sticks can get into the game more easily.[6] The game focuses more on action, as opposed to the more technical gameplay of Tekken, allowing both hardcore and casual fans to enjoy it. As such, players can perform various techniques taken from the Pokémon series, such as special moves and Mega Evolutions (which can be built up from attacks using a \"Synergy Gauge\").[7] Players can also use Support Pokémon to give them special benefits such as buffs in attack or defense. ", "rating": 3, "release": "2016-03-18", "developer": "Bandai Namco Studios", "publisher": "Nintendo & The Pokémon Company", "image": "/static/videogameImages/pokken.png"}, ]
     rpg_videogame = [
         {"name": "Final Fantasy IX", "id": 24, "genre": 1, "description": "The plot centers on the consequences of a war between nations in a medieval fantasy world called Gaia. Players follow bandit Zidane Tribal, who kidnaps Alexandrian princess Garnet Til Alexandros XVII as part of a gambit by the neighboring nation of Lindblum. He joins Garnet and a growing cast of characters on a quest to take down her mother, Queen Brahne of Alexandria, who started the war. The plot shifts when the player learns that Brahne is a pawn of a more menacing threat, Kuja, who shares a mysterious history with Zidane spanning two worlds.", "rating": 3, "release": "2000-07-07", "developer": "Square", "publisher": "Square", "image": "/static/videogameImages/ff9.jpg"},
         {"name": "Pokémon: Let's Go", "id": 25, "genre": 1, "description": "Pokémon: Let's Go, Pikachu! and Let's Go, Eevee! are set in the Kanto region and include more than the original 151 Pokémon creatures in addition to their respective Mega Evolved forms from Pokémon X and Y & Omega Ruby and Alpha Sapphire, and their Alolan Forms from Sun and Moon.", "rating": 3, "release": "2018-11-16", "developer": "Game Freak", "publisher": "The Pokémon Company Nintendo", "image": "/static/videogameImages/letsGoPika.jpg"},
         {"name": "Pokémon Sun", "id": 26, "genre": 1, "description": "As with previous installments, each game follows the journey of a young Pokémon trainer as they train Pokémon. This time, the game takes place in the Alola region—based on Hawaii—with the object of the game being to thwart the schemes of Team Skull, and later the Aether Foundation, all while attempting to challenge various Pokémon trainers of gradually increasing difficulty. Sun and Moon introduced 81 new Pokémon species, and includes new features such as Alolan forms of previous generation Pokémon, powerful moves known as Z-Moves, new, powerful creatures known as Ultra Beasts, updated battle and training mechanics, and improved polygonal 3D graphics.", "rating": 3, "release": "2016-11-18", "developer": "Game Freak", "publisher": "The Pokémon Company Nintendo", "image": "/static/videogameImages/Sun.jpg"},
         {"name": "Horizon Zero Dawn", "id": 27, "genre": 1, "description": "Players take control of Aloy, a hunter who ventures through a post-apocalyptic land ruled by robotic creatures. Aloy can kill enemies in a variety of ways: setting traps like tripwires using the Tripcaster, shooting them with arrows, using explosives, and a spear. Machine components, including electricity and the metal they are composed of, are vital to Aloy's survival; she can loot their remains for crafting resources. Ammo, resource satchels, pouches, quivers; resistance, antidotes, health potions, and traps can all be crafted.", "rating": 4, "release": "2017-02-28", "developer": "Guerrilla Games", "publisher": "Sony Interactive Entertainment", "image": "/static/videogameImages/horizonZeroDawn.jpeg"},
         {"name": "The Witcher 3: Wild Hunt", "id": 28, "genre": 1, "description": "Played in an open world with a third-person perspective, players control protagonist Geralt of Rivia, a monster hunter known as a witcher, who is looking for his missing adopted daughter on the run from the Wild Hunt: an otherworldly force determined to capture and use her powers. Players battle the game's many dangers with weapons and magic, interact with non-player characters, and complete main-story and side quests to acquire experience points and gold, which are used to increase Geralt's abilities and purchase equipment. Its central story has several endings, determined by the player's choices at certain points in the game.", "rating": 4, "release": "2015-05-19", "developer": "CD Projekt Red", "publisher": "CD Projekt", "image": "/static/videogameImages/witcher3.jpg"},
         {"name": "Nier: Automata", "id": 29, "genre": 1, "description": "Nier: Automata is a sequel to the 2010 video game NieR, a spin-off sequel of the Drakengard series. Set in the midst of a proxy war between machines created by otherworldly invaders and the remnants of humanity, the story follows the battles of a combat android, her companion, and a fugitive prototype. Gameplay combines role-playing elements with action-based combat and mixed genre gameplay similar to that of Nier.", "rating": 4, "release": "2017-03-07", "developer": "PlatinumGames", "publisher": "Square Enix", "image": "/static/videogameImages/nierA.jpg"},
         {"name": "Persona 5", "id": 30, "genre": 1, "description": "Persona 5 takes place in modern-day Tokyo and follows the protagonist codenamed Joker after his transfer to Shujin Academy after being put on probation for an assault of which he was falsely accused. During the course of a school year, he and other students awaken to their Persona powers, becoming a group of secret vigilantes known as the Phantom Thieves of Hearts. They explore the Metaverse, a supernatural realm consisting of the physical manifestation of humanity's subconscious desires, to change malevolent intent from the hearts of adults. As with previous titles in the series, the party battles enemies known as Shadows using physical manifestations of their psyche, called Personas. The game incorporates role-playing and dungeon crawling elements alongside social simulation scenarios.", "rating": 3, "release": "2017-04-04", "developer": "P-Studio", "publisher": "Atlus", "image": "/static/videogameImages/p5.jpg"},
         {"name": "Bloodborne", "id": 31, "genre": 1, "description": "Bloodborne follows the player character, the Hunter, through the decrepit Gothic, Victorian era-inspired city of Yharnam, whose inhabitants have been afflicted with an abnormal blood-borne disease, with the player character unraveling the city's intriguing mysteries while fighting beasts, ultimately attempting to find the source of the plague and stop it.", "rating": 3, "release": "2015-03-24", "developer": "FromSoftware", "publisher": "Sony Computer Entertainment", "image": "/static/videogameImages/bloodborne.jpg"},
         {"name": "Assassin's Creed Odyssey", "id": 32, "genre": 1, "description": "Set in the year 431 BC, the plot tells a fictional history of the Peloponnesian War between Athens and Sparta. Players control a male or female mercenary (Ancient Greek: μίσθιος misthios) who fights for both sides as they attempt to unite their family and uncover a malign cult.", "rating": 3, "release": "2018-10-05", "developer": "Ubisoft Quebec", "publisher": "Ubisoft", "image": "/static/videogameImages/creedOd.jpeg"},
         {"name": "Monster Hunter: World", "id": 33, "genre": 1, "description": "In the game, the player takes the role of a Hunter, tasked to hunt down and either kill or trap monsters that roam in one of several environmental spaces. If successful, the player is rewarded through loot consisting of parts from the monster and other elements that are used to craft weapons and armor, amongst other equipment. The game's core loop has the player crafting appropriate gear to be able to hunt down more difficult monsters, which in turn provide parts that lead to more powerful gear. Players may hunt alone, or can hunt in cooperative groups of up to four players via the game's online services.", "rating": 3, "release": "2018-01-26", "developer": "Capcom", "publisher": "Capcom", "image": "/static/videogameImages/monHunWorld.jpeg"},
         {"name": "Fallout 4", "id": 34, "genre": 1, "description": "The player assumes control of a character referred to as the \"Sole Survivor\", who emerges from a long-term cryogenic stasis in Vault 111, an underground nuclear fallout shelter. After witnessing the murder of their spouse and kidnapping of their son, the Sole Survivor ventures out into the Commonwealth to search for their missing child. The player explores the game's dilapidated world, completes various quests, helps out factions, and acquires experience points to level up and increase the abilities of their character. New features to the series include the ability to develop and manage settlements and an extensive crafting system where materials scavenged from the environment can be used to craft drugs and explosives, upgrade weapons and armor, and construct, furnish and improve settlements. Fallout 4 also marks the first game in the series to feature full voice acting for the protagonist.", "rating": 3, "release": "2015-11-10", "developer": "Bethesda Game Studios", "publisher": "Bethesda Softworks", "image": "/static/videogameImages/fallout4.jpg"},
         {"name": "Final Fantasy XV", "id": 35, "genre": 1, "description": "Final Fantasy XV takes place on the fictional world of Eos; aside from the capital of Lucis, all the world is dominated by the empire of Niflheim, who seek control of the magical Crystal protected by Lucis's royal family. On the eve of peace negotiations, Niflheim attacks the capital and steals the Crystal. Noctis Lucis Caelum, heir to the Lucian throne, goes on a quest to rescue the Crystal and defeat Niflheim. He later learns his full role as the \"True King\", destined to use the Crystal's powers to save Eos from eternal darkness. ", "rating": 3, "release": "2016-11-29", "developer": "Square Enix Business Division 2", "publisher": "Square Enix", "image": "/static/videogameImages/ff15.jpg"},
         {"name": "Dark Souls III", "id": 36, "genre": 1, "description": "Set in the Kingdom of Lothric, a bell has rung to signal that the First Flame, responsible for maintaining the Age of Fire, is dying out. As has happened many times before, the coming of the Age of Dark produces the undead: cursed beings that rise up after death. The Age of Fire can be prolonged with the linking of the fire, a ritual in which great lords and heroes sacrifice their souls to rekindle the First Flame. However, Prince Lothric, the chosen linker for this age, has abandoned his duty and instead chooses to watch the flame die from afar. The bell is the last hope for the Age of Fire, resurrecting previous Lords of Cinder (heroes who linked the flame in past ages) to attempt to link the fire again; however, all but one Lord shirk their duty.", "rating": 3, "release": "2016-04-12", "developer": "FromSoftware", "publisher": "Bandai Namco Entertainment", "image": "/static/videogameImages/dSouls3.jpg"},
         {"name": "Kingdom Hearts III", "id": 37, "genre": 1, "description": "It is the twelfth installment in the Kingdom Hearts series, a sequel to Kingdom Hearts II, and the final chapter in the Dark Seeker saga. Set after the events of Kingdom Hearts 3D: Dream Drop Distance, returning protagonist Sora is joined by Donald Duck, Goofy, King Mickey and Riku in their search for the seven Guardians of Light and the \"Key to Return Hearts\" as they attempt to thwart the restored Xehanort's plan to bring about a second Keyblade War. Their journey has them cross paths with characters and visit worlds based on different Disney and Pixar properties.", "rating": 3, "release": "2019-01-29", "developer": "Square Enix Business Division 3", "publisher": "Square Enix", "image": "/static/videogameImages/kh3.jpg"},
         {"name": "Tales of Zestiria", "id": 38, "genre": 1, "description": "The story follows Sorey, a young man blessed with powers by a mystical spirit race known as the Seraphim who act as a stabilizing force in the land, as he travels to free the land of Glenwood from the threat of the Hellion, creatures spawned by negative emotions. \"RPG of Passion Lighting the World\"), with its story focusing on the passion of the characters.", "rating": 3, "release": "2015-01-22", "developer": "Bandai Namco Studios", "publisher": "Bandai Namco Entertainment", "image": "/static/videogameImages/talesOfZ.jpg"},]

     platform_videogame = [
         {"name": "Super Mario World", "id": 39, "genre": 1, "description": "Super Mario World is a 1990 side-scrolling platform game developed and published by Nintendo for the Super Nintendo Entertainment System. The story follows Mario's quest to save Princess Toadstool and Dinosaur Land from the series antagonist Bowser and his children, the Koopalings.", "rating": 4, "release": "1990-11-21", "developer": "Nintendo", "publisher": "Nintendo", "image": "/static/videogameImages/superMarioWorld.jpg"},
         {"name": "Super Mario Bros. 3", "id": 40, "genre": 1, "description": "Players control plumbers Mario or Luigi, who must save Princess Toadstool and the rulers of seven different kingdoms from the antagonist Bowser. As in previous Mario games, they defeat enemies by stomping them or using items that bestow magical powers; they also have new abilities, including flight or sliding down slopes. Super Mario Bros. 3 introduces many elements that became Mario staples, such as Bowser's children the Koopalings and a world map to transition between levels.", "rating": 4, "release": "1990-02-12", "developer": "Nintendo", "publisher": "Nintendo", "image": "/static/videogameImages/super-mario-bros-3-cover.jpg"},
         {"name": "Portal", "id": 41, "genre": 1, "description": "Portal consists primarily of a series of puzzles that must be solved by teleporting the player's character and simple objects using \"the Aperture Science Handheld Portal Device\", a device that can create inter-spatial portals between two flat planes. The player-character, Chell, is challenged and taunted by an artificial intelligence named GLaDOS (Genetic Lifeform and Disk Operating System) to complete each puzzle in the Aperture Science Enrichment Center using the portal gun with the promise of receiving cake when all the puzzles are completed.", "rating": 3, "release": "2007-10-10", "developer": "Valve Corporation", "publisher": "Valve Corporation", "image": "/static/videogameImages/portal.jpg"},
         {"name": "Super Mario Odyssey", "id": 42, "genre": 1, "description": "An entry in the Super Mario series, it follows Mario and Cappy, a spirit that turns into Mario's hat and allows him to possess other characters and objects, as they journey across various worlds to save Princess Peach from his nemesis Bowser, who plans to forcibly marry her. In contrast to the linear gameplay of prior entries, the game returns to the primarily open-ended, exploration-based gameplay featured in Super Mario 64 and Super Mario Sunshine.", "rating": 3, "release": "2017-10-27", "developer": "Nintendo EPD", "publisher": "Nintendo", "image": "/static/videogameImages/supermarioodyssey.jpg"},
         {"name": "DuckTales", "id": 43, "genre": 1, "description": "Players control Scrooge McDuck as he travels around the world and outer space in search of five treasures to further increase his fortune. Scrooge is able to attack enemies and get around using his cane. On the ground, Scrooge can swing his cane to attack enemies and to break open or throw certain objects. While jumping, Scrooge can bounce on his cane similarly to a pogo stick and attack enemies from above. This also allows him to reach higher areas as well as bounce across hazardous areas that would hurt him on foot. Along the way, Scrooge can find various diamonds, hidden inside treasure chests or appearing in certain areas, to increase his fortune and ice cream that can restore his health. Scrooge will also encounter various characters from the series who have a variety roles, such as providing hints, offering useful items, opening access to new areas, or attempting to stop Scrooge's progress.", "rating": 3, "release": "1990-01-26", "developer": "Capcom", "publisher": "Capcom", "image": "/static/videogameImages/duckTales.png"},
         {"name": "Ape Escape", "id": 44, "genre": 1, "description": "One of the main story elements of each of the main series involves a white-haired monkey named Specter obtaining a helmet known as the Peak Point Helmet (Pipo Helmet for short), which boosts his intelligence. After equipping an army of monkeys with Pipo Helmets, and using an enhanced helmet for himself, Specter sends his monkey army to take over the world, and Space. It is up to the game's protagonists, equipped with various gadgets, to capture the monkeys and restore order to the world.", "rating": 3, "release": "2019-02-15", "developer": "SCE Japan Studio", "publisher": "Sony Computer Entertainment & Ubisoft", "image": "/static/videogameImages/Ape_Escape.jpg"},
         {"name": "Sly Cooper and the Thievius Raccoonus", "id": 45, "genre": 1, "description": "The game focuses on master thief Sly Cooper and his gang, Bentley the Turtle and Murray the Hippo, as they seek out the Fiendish Five to recover his family's \"Thievius Raccoonus,\" a book with the accumulation of all of Sly's ancestors' thieving moves.", "rating": 3, "release": "1999-05-31", "developer": "Sucker Punch Productions", "publisher": "Sony Computer Entertainment", "image": "/static/videogameImages/slyCooper.png"},
         {"name": "Spyro: Year of the Dragon", "id": 46, "genre": 1, "description": "Named after the animal of the Chinese zodiac, which was the symbol at the time of the game's release, Year of the Dragon follows the titular purple dragon Spyro as he travels to the \"Forgotten Worlds\" after 150 magical dragon eggs are stolen from the land of the dragons by an evil sorceress. Players travel across thirty different worlds gathering gems and eggs. Year of the Dragon introduced new characters and minigames to the series, as well as offering improved graphics and music.", "rating": 3, "release": "2000-10-24", "developer": "Insomniac Games", "publisher": "Sony Computer Entertainment", "image": "/static/videogameImages/spyro.png"},
         {"name": "Banjo-Kazooie", "id": 47, "genre": 1, "description": "It is the first game in the Banjo-Kazooie series and follows the story of a bear, Banjo, and a bird, Kazooie, as they try to stop the plans of the witch Gruntilda, who intends to switch her beauty with Banjo's sister, Tooty. The game features nine nonlinear levels where the player must use Banjo and Kazooie's wide range of abilities to gather jigsaw pieces. It features challenges like solving puzzles, jumping over obstacles, collecting items, and defeating opponents.", "rating": 3, "release": "1998-06-29", "developer": "Rare", "publisher": "Nintendo & Microsoft Game Studios", "image": "/static/videogameImages/banjo.jpg"},  ]
     shooter_videogame = [
         {"name": "Fortnite", "id": 48, "genre": 1, "description": "Fortnite: Save the World is designed as player-versus-environment game, with four players cooperating towards a common objective on various missions. The game is set after a fluke storm appears across Earth, causing 98% of the population to disappear, and the survivors to be attacked by zombie-like \"husks\". The players take the role of commanders of home base shelters, collecting resources, saving survivors, and defending equipment that help to either collect data on the storm or to push back the storm. From missions, players are awarded a number of in-game items, which include hero characters, weapon and trap schematics, and survivors, all of which can be leveled up through gained experience to improve their attributes. Fortnite Battle Royale is a player-versus-player battle royale game for up to 100 players, allowing one to play alone, in a duo, or in a squad (usually consisting of three or four players). Weaponless players airdrop from a \"Battle Bus\" that crosses the game's map. When they land, they must scavenge for weapons, items, resources, and even vehicles while trying to stay alive and attack other players, eliminating them. Over the course of a round, the safe area of the map shrinks down in size due to an incoming storm; players outside that safe area take damage and can be eliminated if they fail to quickly evacuate. This forces remaining players into tighter spaces and encourages player encounters. The last player, duo, or squad remaining is the winner. Fortnite Creative is a sandbox game mode where players are given complete freedom to create anything they want on an island, such as battle arenas, race courses, platforming challenges and more. Epic Games plans to review some of the most popular creations from Creative and rotate these into the Battle Royale map in an area called \"The Block\".", "rating": 3, "release": "2017-07-25", "developer": "Epic Games", "publisher": "Epic Games", "image": "/static/videogameImages/fortnite.jpg"},
         {"name": "Resident Evil 7: Biohazard", "id": 49, "genre": 1, "description": "Resident Evil 7 returns to the franchise's survival horror roots, emphasizing exploration. The player controls Ethan Winters as he searches for his wife in a derelict plantation occupied by a cannibal family, solving puzzles and fighting enemies. It is the first main series game to use a first-person view.", "rating": 3, "release": "2017-01-24", "developer": "Capcom", "publisher": "Capcom", "image": "/static/videogameImages/resEvilBio.jpg"},
         {"name": "Battlefield 1", "id": 50, "genre": 1, "description": "Similar to its predecessors, Battlefield 1 is a first-person shooter game that emphasizes teamwork. It is set in the period of World War I, and is inspired by historical events. Players can make use of World War I weapons, including bolt-action rifles, submachine guns, automatic and semi-automatic rifles, artillery, flamethrowers, and mustard gas to combat opponents.", "rating": 3, "release": "2016-10-21", "developer": "	EA DICE", "publisher": "Electronic Arts", "image": "/static/videogameImages/bField1.jpg"},
         {"name": "Destiny 2", "id": 51, "genre": 1, "description": "Set in a \"mythic science fiction\" world, the game features a multiplayer \"shared-world\" environment with elements of role-playing games. Like the original, activities in Destiny 2 are divided among player versus environment (PvE) and player versus player (PvP) game types. In addition to normal story missions, PvE features three-player \"strikes\" and six-player raids. A free roam patrol mode is also available for each planet and features public events as well as new activities not featured in the original. These new activities have an emphasis on exploration of the planets and interactions with non-player characters (NPCs); the original Destiny only featured NPCs in social spaces. PvP features objective-based modes, as well as traditional deathmatch game modes.", "rating": 3, "release": "2017-09-06", "developer": "Bungie", "publisher": "Activision", "image": "/static/videogameImages/d2.jpg"},
         {"name": "Titanfall 2", "id": 52, "genre": 1, "description": "In Titanfall 2, players control Titans, mecha-style exoskeletons and their pilots, who are agile and equipped with a variety of skills ranging from wall-running to cloaking. Set in a science fiction universe, the single-player campaign follows the story of Jack Cooper, a rifleman from Frontier Militia, who bonds with his Titan BT-7274 after an accident. Together, they embark on a quest to stop the Interstellar Manufacturing Corporation (IMC) from launching a superweapon.", "rating": 3, "release": "2017-01-24", "developer": "Respawn Entertainment", "publisher": "Electronic Arts", "image": "/static/videogameImages/titanfall.jpg"},
         {"name": "Doom", "id": 53, "genre": 1, "description": "The series focuses on the exploits of an unnamed space marine operating under the auspices of Union Aerospace Corporation (UAC), who fights hordes of demons and the undead in order to survive.", "rating": 3, "release": "2017-12-01", "developer": "id Software", "publisher": "Bethesda Softworks", "image": "/static/videogameImages/doom.png"},
         {"name": "Overwatch", "id": 54, "genre": 1, "description": "Described as a \"hero shooter\", Overwatch assigns players into two teams of six, with each player selecting from a roster of nearly 30 characters, known as \"heroes\", each with a unique style of play whose roles are divided into three general categories that fit their role. Players on a team work together to secure and defend control points on a map or escort a payload across the map in a limited amount of time.", "rating": 3, "release": "2016-05-24", "developer": "Blizzard Entertainment", "publisher": "Blizzard Entertainment", "image": "/static/videogameImages/overwatch.jpg"},
         {"name": "Far Cry New Dawn", "id": 55, "genre": 1, "description": "The player will assume the role of a new character, whose gender and race can be customized. The Guns for Hire and the Fangs for Hire systems from Far Cry 5 return, with the character being able to recruit human survivors and animals for combat assistance. In addition to new characters, the game's cast includes an array of returning characters from Far Cry 5. The player character can also encounter several specialists who have their own personal missions, special abilities and story and help players to repair their weapons. New weapons are introduced in the game, including a \"Saw Launcher\" that fires the blades of circular saws. Players acquire new weapons and attachments, which can be upgraded to three different levels through crafting and finishing missions. Vehicles can also be crafted.", "rating": 3, "release": "2019-02-15", "developer": "Ubisoft Montreal", "publisher": "Ubisoft", "image": "/static/videogameImages/fcNewDawn.jpg"}, ]

     action = {
        "Adventure": {"genre_id": 2000, "name": "Adventure", "VideoGame": adventure_videogame},
        "Fighting": {"genre_id": 3000, "name": "Fighting", "VideoGame": fighting_videogame},
        "RPG": {"genre_id": 4000, "name": "RPG", "VideoGame": rpg_videogame},
        "Platform": {"genre_id": 5000, "name": "Platform", "VideoGame": platform_videogame},
        "First-Person Shooter": {"genre_id": 6000, "name": "First-Person Shooter", "VideoGame": shooter_videogame} }

     for cat, cat_data in action.items():
         v = add_genre(cat_data["genre_id"], cat_data["name"])
         for g in cat_data["VideoGame"]:
             add_videogame(g["name"], g["id"], v, g["description"], g["rating"], g["release"], g["developer"], g["publisher"], g["image"])


def add_genre(id, name):
    g = Genre.objects.get_or_create(genre_id=id, name=name)[0]
    g.save()
    print(g.genre_id);
    print(g.name);
    return g

def add_videogame(name, id, genre, description, rating, release, developer, publisher, image):
    print(name);
    print(id);
    print(genre);
    print(description);
    print(rating);
    print(release);
    print(developer);
    print(publisher);
    print(image);
    v = VideoGame.objects.get_or_create(name=name, slug=slugify(name), id=id, genre=genre, description=description, rating=rating, release=release, developer=developer, publisher=publisher, image=image)[0]
    v.save()
    return v


if __name__ == '__main__':
    print("Starting NoobNews population script...")
    populate()
