# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-19 20:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ratingValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviews_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('comments', models.CharField(max_length=300)),
                ('publish_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('comment_rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile_image', models.ImageField(default='NoProfile.jpg', upload_to='static/profile_images')),
                ('game_library_image', models.ImageField(default='default_videogame.jpg', upload_to='static/video_game_default')),
                ('player_tag', models.CharField(max_length=128, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.CharField(max_length=300)),
                ('rating', models.IntegerField(default=0)),
                ('release', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('developer', models.CharField(max_length=128)),
                ('publisher', models.CharField(max_length=128)),
                ('image', models.ImageField(default='', upload_to='')),
                ('youtubeurl', models.CharField(max_length=300)),
                ('speedRun', models.CharField(max_length=300)),
                ('trivia', models.CharField(default='There are no Trivia available for this game at the moment', max_length=300)),
                ('cheats', models.CharField(default='There are no Cheats available for this game at the moment', max_length=300)),
                ('easter_eggs', models.CharField(default='There are no Easter Eggs available for this game at the moment', max_length=300)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noobnews.Genre')),
            ],
            options={
                'verbose_name_plural': 'videogames',
            },
        ),
        migrations.CreateModel(
            name='VideoGameList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_library_image', models.ImageField(default='default_videogame.jpg', upload_to='static/video_game_default')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='noobnews.UserProfile')),
                ('userLibrary', models.ManyToManyField(blank=True, to='noobnews.VideoGame')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='videogame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noobnews.VideoGame'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noobnews.UserProfile'),
        ),
        migrations.AddField(
            model_name='review',
            name='videogame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noobnews.VideoGame'),
        ),
    ]
