# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-12 16:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('reviews_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('comments', models.CharField(max_length=300)),
                ('publish_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('player_tag', models.CharField(max_length=128, unique=True)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('profile_image', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=300)),
                ('rating', models.IntegerField(default=0)),
                ('release', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('developer', models.CharField(max_length=128)),
                ('publisher', models.CharField(max_length=128)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noobnews.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='VideoGameList',
            fields=[
                ('list_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noobnews.User')),
                ('videogame_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noobnews.VideoGame')),
            ],
        ),
        migrations.AddField(
            model_name='reviews',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noobnews.User'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='videogame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noobnews.VideoGame'),
        ),
    ]
