# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogamelist',
            name='list_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
