# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-20 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
