# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0002_auto_20190212_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='image',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
