# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-17 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0003_userprofile_game_library_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='game_library_image',
        ),
    ]
