# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-12 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0003_auto_20190312_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videogame',
            old_name='easter',
            new_name='easter_eggs',
        ),
    ]
