# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-13 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0003_videogame_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
