# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-15 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0004_auto_20190312_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_image',
            field=models.ImageField(default='NoProfile.jpg', upload_to='media/static/profile_images'),
        ),
    ]
