# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-15 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0004_auto_20190213_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
