# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-17 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0004_remove_userprofile_game_library_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='game_library_image',
            field=models.ImageField(default='default_videogame.jpg', upload_to='static/video_game_default'),
        ),
    ]
