# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-15 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0005_videogame_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videogame',
            options={'verbose_name_plural': 'VideoGames'},
        ),
    ]
