# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-15 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0006_auto_20190215_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videogame',
            options={'verbose_name_plural': 'videogames'},
        ),
        migrations.AlterField(
            model_name='videogame',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
