# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-15 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0007_auto_20190215_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
