# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-15 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0005_auto_20190214_1844'),
        ('noobnews', '0008_auto_20190215_1444'),
    ]

    operations = [
    ]
