# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-17 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0009_merge_20190215_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_profile_image',
            field=models.ImageField(blank=True, default='profile_images/default-user.png', upload_to='profile_images'),
        ),
    ]
