# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-17 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0011_videogame_youtubeurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='speedRun',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
