# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0012_videogame_speedrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_image',
            field=models.ImageField(blank=True, default='profile_images/default-user.png', upload_to='static/profile_images'),
        ),
    ]
