# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-24 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0013_auto_20190219_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='comment_rating',
        ),
    ]
