# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-25 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0016_auto_20190225_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='NoProfile.jpg', upload_to='profile_pics'),
        ),
    ]
