# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-25 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0017_auto_20190225_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='user_profile_image',
        ),
    ]
