# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0018_auto_20190225_1921'),
        ('noobnews', '0014_auto_20190224_1636'),
    ]

    operations = [
    ]
