# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-12 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0019_auto_20190226_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='trivia',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
