# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-12 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0019_auto_20190226_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='ratingValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='videogame',
            name='cheatPicture',
            field=models.CharField(default='There is no Cheats available for this game at the moment', max_length=300),
        ),
        migrations.AddField(
            model_name='videogame',
            name='cheats',
            field=models.CharField(default='There is no Cheats available for this game at the moment', max_length=300),
        ),
        migrations.AddField(
            model_name='videogame',
            name='creditPicture',
            field=models.CharField(default='There is no Credits available for this game at the moment', max_length=300),
        ),
        migrations.AddField(
            model_name='videogame',
            name='credits',
            field=models.CharField(default='There is no Credits available for this game at the moment', max_length=300),
        ),
        migrations.AddField(
            model_name='videogame',
            name='trivia',
            field=models.CharField(default='There is no Trivia available for this game at the moment', max_length=300),
        ),
        migrations.AddField(
            model_name='videogame',
            name='triviaPicture',
            field=models.CharField(default='There is no Trivia available for this game at the moment', max_length=300),
        ),
        migrations.AddField(
            model_name='score',
            name='videogame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noobnews.VideoGame'),
        ),
    ]
