# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-12 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0020_videogame_trivia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ratingValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('videogame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noobnews.VideoGame')),
            ],
        ),
        migrations.CreateModel(
            name='VideoExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trivia', models.CharField(default='There is no Trivia available for this game at the moment', max_length=300)),
                ('cheats', models.CharField(default='There is no Cheats available for this game at the moment', max_length=300)),
                ('credits', models.CharField(default='There is no Credits available for this game at the moment', max_length=300)),
                ('triviaPicture', models.CharField(default='There is no Trivia available for this game at the moment', max_length=300)),
                ('cheatPicture', models.CharField(default='There is no Cheats available for this game at the moment', max_length=300)),
                ('creditPicture', models.CharField(default='There is no Credits available for this game at the moment', max_length=300)),
                ('videogame_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noobnews.VideoGame')),
            ],
        ),
    ]
