# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-12 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noobnews', '0021_ratingvalue_score_videoextrainfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoextrainfo',
            name='cheatPicture',
        ),
        migrations.RemoveField(
            model_name='videoextrainfo',
            name='cheats',
        ),
        migrations.RemoveField(
            model_name='videoextrainfo',
            name='creditPicture',
        ),
        migrations.RemoveField(
            model_name='videoextrainfo',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='videoextrainfo',
            name='trivia',
        ),
        migrations.RemoveField(
            model_name='videoextrainfo',
            name='triviaPicture',
        ),
        migrations.AddField(
            model_name='videogame',
            name='cheats',
            field=models.CharField(default='There are no Cheats available for this game at the moment', max_length=300),
        ),
        migrations.AddField(
            model_name='videogame',
            name='easter_eggs',
            field=models.CharField(default='There are no Easter Eggs available for this game at the moment', max_length=300),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='trivia',
            field=models.CharField(default='There are no Trivia available for this game at the moment', max_length=300),
        ),
    ]
